development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: dumplings_development
  pool: 9
  username: root
  password: namor07
  timeout: 5000
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: dumplings_test
  pool: 9
  username: root
  password:
  timeout: 5000
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: dumplings_production
  pool: 9
  username: root
  password:
  timeout: 5000
  socket: /tmp/mysql.sock
